# Generated by Claude AI

import re


class IPAddress(str):
	def __new__(cls, value: str) -> "IPAddress":
		# Validate IP format
		ip_pattern = r"^(\d{1,3}\.){3}\d{1,3}$"
		if not re.match(ip_pattern, value):
			raise ValueError(f"Invalid IP address format: {value}")

		# Validate octet ranges
		octets = value.split(".")
		if not all(0 <= int(octet) <= 255 for octet in octets):
			raise ValueError(f"IP address octets must be 0-255: {value}")

		return super().__new__(cls, value)
